name: CI Pipeline

# Trigger the workflow on push to main and feature_microservice branches
on:
  push:
    branches:
      - main
      - feature_microservice

jobs:
  
  build:
    
    runs-on: 
      - self-hosted
      - windows
      - minikube

    env:
      # Set environment variables for Docker image names and tags
      BACKEND_IMAGE: ghcr.io/${{ github.repository_owner }}/backend-api
      FRONTEND_IMAGE: ghcr.io/${{ github.repository_owner }}/frontend-app
      IMAGE_TAG: ${{ github.sha }}
      DOCKER_HOST: ""
      DOCKER_TLS_VERIFY: ""
      DOCKER_CERT_PATH: ""

    permissions:
      contents: read
      packages: write

    steps:

      # Download repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Reset Docker context to Desktop deamon before building and pushing images to GitHub Container Registry
      - name: Reset Docker Context
        shell: powershell
        run: |
          docker context use default
          docker context ls
          docker version

      # Authenticate with GitHub Container Registry
      - name: Authenticate with GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.minikube-ghcr-pull }}

      #========================================
      # Backend Image
      #========================================

      # Build backend Docker image with both commit SHA and latest tags for pushing to GitHub Container Registry
      - name: Build Backend Image
        shell: powershell
        run: |
          docker build `
          -t "$env:BACKEND_IMAGE`:$env:IMAGE_TAG" `
          -t "$env:BACKEND_IMAGE`:latest" `
          ./backend
      
      # Push backend Docker image to GitHub Container Registry
      - name: Push Backend Image
        shell: powershell
        run: |
          docker push "$env:BACKEND_IMAGE`:$env:IMAGE_TAG"
          docker push "$env:BACKEND_IMAGE`:latest"
      
      #========================================
      # Frontend Image
      #========================================

      # Build frontend Docker image with both commit SHA and latest tags for pushing to GitHub Container Registry
      - name: Build Frontend Image
        shell: powershell
        run: |
          docker build `
          -t "$env:FRONTEND_IMAGE`:$env:IMAGE_TAG" `
          -t "$env:FRONTEND_IMAGE`:latest" `
          ./frontend
      # Push frontend Docker image to GitHub Container Registry
      - name: Push Frontend Image
        shell: powershell
        run: |
          docker push "$env:FRONTEND_IMAGE`:$env:IMAGE_TAG"
          docker push "$env:FRONTEND_IMAGE`:latest"