name: CI Pipeline

# Trigger the workflow on push to main and feature_microservice branches
on:
  push:
    branches:
      - main
      - feature_microservice

jobs:
  
  build:
    
    # Github linux runner
    runs-on: 
      # - ubuntu-latest
      - self-hosted
      - windows
      - minikube

    permissions:
      contents: read
      packages: write

    steps:

      # Download repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Reset Docker context to Desktop deamon before building and pushing images to GitHub Container Registry
      - name: Reset Docker Context
        shell: powershell
        run: |
          Remove-Item Env:DOCKER_HOST `
          -ErrorAction SilentlyContinue

          Remove-Item Env:DOCKER_TLS_VERIFY `
          -ErrorAction SilentlyContinue

          Remove-Item Env:DOCKER_CERT_PATH `
          -ErrorAction SilentlyContinue

          docker context use default

          docker context ls

          docker version

      # Authenticate with GitHub Container Registry
      - name: Authenticate with GitHub Container Registry
        uses: docker/login-action@v3
        with:
          
          # GitHub registry URL
          registry: ghcr.io

          # Current GitHub user
          username: ${{ github.actor }}

          # Github auto-generated token for authentication
          password: ${{ secrets.GITHUB_TOKEN }}

      #========================================
      # Backend Image
      #========================================

      # Build backend Docker image with both commit SHA and latest tags for pushing to GitHub Container Registry
      - name: Build Backend Image
        shell: powershell
        run: |
          docker build `
          -t ghcr.io/${{ github.repository_owner }}/backend-api:${{ github.sha }} `
          -t ghcr.io/${{ github.repository_owner }}/backend-api:latest `
          ./backend
      
      # Push backend Docker image to GitHub Container Registry
      - name: Push Backend Image
        shell: powershell
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend-api:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/backend-api:latest
      
      #========================================
      # Frontend Image
      #========================================

      # Build frontend Docker image with both commit SHA and latest tags for pushing to GitHub Container Registry
      - name: Build Frontend Image
        shell: powershell
        run: |
          docker build `
          -t ghcr.io/${{ github.repository_owner }}/frontend-app:${{ github.sha }} `
          -t ghcr.io/${{ github.repository_owner }}/frontend-app:latest `
          ./frontend
      # Push frontend Docker image to GitHub Container Registry
      - name: Push Frontend Image
        shell: powershell
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/frontend-app:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/frontend-app:latest

    # Registry propagation safety    
    # Wait for a short period to ensure that the pushed images are available in the registry before proceeding with deployment
      - name: Wait Registry Sync
        shell: powershell
        run: | 
          Start-Sleep -Seconds 10